---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: carbon-jessie

inputs:
  - name: hello_hapi
  - name: dependency-cache

run:
  path: hello_hapi/ci/scripts/run_tests.sh
